name = "example"
tags = []

[[actions]]
name = "Stow core dotfiles"
kind = "stow"
kwargs.package = "core"

[[actions]]
name = "Install core packages (linux)"
kind = "apt"
tags = ["linux"]
kwargs.packages = ["fzf", "zsh"]

[[actions]]
name = "Install core packages (macos)"
kind = "brew"
tags = ["macos"]
kwargs.packages = ["fzf"]

[[actions]]
name = "Install ZSH plugins"
kind = "github"
kwargs.sources = [
  "zsh-users/zsh-syntax-highlighting",
  "zsh-users/zsh-autosuggestions",
  "jeffreytse/zsh-vi-mode",
]
kwargs.dest = "{home}/.local/share/zsh"
