name = "example"
tags = []

[[actions]]
name = "Stow core dotfiles"
kind = "stow"
kwargs.package = "core"

[[actions]]
name = "Install core packages (linux)"
kind = "apt"
tags = ["linux"]
kwargs.packages = ["fzf", "zsh"]

[[actions]]
name = "Install core packages (macos)"
kind = "brew"
tags = ["macos"]
kwargs.packages = ["fzf"]

[[actions]]
name = "Install ZSH syntax highlighting"
kind = "github"
kwargs.source = "zsh-users/zsh-syntax-highlighting"
kwargs.dest = "{home}/.local/share/zsh"
